// Liste des pays : code ISO, nom francais, indicatif. Le drapeau se deduit du
// code ISO et s affiche en SVG (voir components/ui/drapeau).
export interface Country {
    code: string;       // ISO 3166-1 alpha-2
    name: string;       // French name
    dial: string;       // International dialing code
}

export const COUNTRIES: Country[] = [
    { code: "AC", name: "Île de l'Ascension", dial: "+247" },
    { code: "AD", name: "Andorre", dial: "+376" },
    { code: "AE", name: "Émirats Arabes Unis", dial: "+971" },
    { code: "AF", name: "Afghanistan", dial: "+93" },
    { code: "AG", name: "Antigua et Barbuda", dial: "+1" },
    { code: "AI", name: "Anguilla", dial: "+1" },
    { code: "AL", name: "Albanie", dial: "+355" },
    { code: "AM", name: "Arménie", dial: "+374" },
    { code: "AO", name: "Angola", dial: "+244" },
    { code: "AR", name: "Argentine", dial: "+54" },
    { code: "AS", name: "Samoa américaines", dial: "+1" },
    { code: "AT", name: "Autriche", dial: "+43" },
    { code: "AU", name: "Australie", dial: "+61" },
    { code: "AW", name: "Aruba", dial: "+297" },
    { code: "AX", name: "Île d'Åland", dial: "+358" },
    { code: "AZ", name: "Azerbaïdjan", dial: "+994" },
    { code: "BA", name: "Bosnie-Herzégovine", dial: "+387" },
    { code: "BB", name: "Barbade", dial: "+1" },
    { code: "BD", name: "Bangladesh", dial: "+880" },
    { code: "BE", name: "Belgique", dial: "+32" },
    { code: "BF", name: "Burkina Faso", dial: "+226" },
    { code: "BG", name: "Bulgarie", dial: "+359" },
    { code: "BH", name: "Bahreïn", dial: "+973" },
    { code: "BI", name: "Burundi", dial: "+257" },
    { code: "BJ", name: "Bénin", dial: "+229" },
    { code: "BL", name: "Saint-Barthélemy", dial: "+590" },
    { code: "BM", name: "Bermudes", dial: "+1" },
    { code: "BN", name: "Brunéi", dial: "+673" },
    { code: "BO", name: "Bolivie", dial: "+591" },
    { code: "BQ", name: "Pays-Bas caribéens", dial: "+599" },
    { code: "BR", name: "Brésil", dial: "+55" },
    { code: "BS", name: "Bahamas", dial: "+1" },
    { code: "BT", name: "Bhoutan", dial: "+975" },
    { code: "BW", name: "Botswana", dial: "+267" },
    { code: "BY", name: "Biélorussie", dial: "+375" },
    { code: "BZ", name: "Belize", dial: "+501" },
    { code: "CA", name: "Canada", dial: "+1" },
    { code: "CC", name: "Îles Cocos", dial: "+61" },
    { code: "CD", name: "République Démocratique du Congo", dial: "+243" },
    { code: "CF", name: "Centrafrique", dial: "+236" },
    { code: "CG", name: "Congo (République)", dial: "+242" },
    { code: "CH", name: "Suisse", dial: "+41" },
    { code: "CI", name: "Côte d'Ivoire", dial: "+225" },
    { code: "CK", name: "Îles Cook", dial: "+682" },
    { code: "CL", name: "Chili", dial: "+56" },
    { code: "CM", name: "Cameroun", dial: "+237" },
    { code: "CN", name: "Chine", dial: "+86" },
    { code: "CO", name: "Colombie", dial: "+57" },
    { code: "CR", name: "Costa Rica", dial: "+506" },
    { code: "CU", name: "Cuba", dial: "+53" },
    { code: "CV", name: "Cap-Vert", dial: "+238" },
    { code: "CW", name: "Curaçao", dial: "+599" },
    { code: "CX", name: "Île Christmas", dial: "+61" },
    { code: "CY", name: "Chypre", dial: "+357" },
    { code: "CZ", name: "Tchéquie", dial: "+420" },
    { code: "DE", name: "Allemagne", dial: "+49" },
    { code: "DJ", name: "Djibouti", dial: "+253" },
    { code: "DK", name: "Danemark", dial: "+45" },
    { code: "DM", name: "Dominique", dial: "+1" },
    { code: "DO", name: "République Dominicaine", dial: "+1" },
    { code: "DZ", name: "Algérie", dial: "+213" },
    { code: "EC", name: "Équateur", dial: "+593" },
    { code: "EE", name: "Estonie", dial: "+372" },
    { code: "EG", name: "Égypte", dial: "+20" },
    { code: "EH", name: "Sahara Occidental", dial: "+212" },
    { code: "ER", name: "Érythrée", dial: "+291" },
    { code: "ES", name: "Espagne", dial: "+34" },
    { code: "ET", name: "Éthiopie", dial: "+251" },
    { code: "FI", name: "Finlande", dial: "+358" },
    { code: "FJ", name: "Fidji", dial: "+679" },
    { code: "FK", name: "Îles Malouines", dial: "+500" },
    { code: "FM", name: "Micronésie", dial: "+691" },
    { code: "FO", name: "Îles Féroé", dial: "+298" },
    { code: "FR", name: "France", dial: "+33" },
    { code: "GA", name: "Gabon", dial: "+241" },
    { code: "GB", name: "Royaume-Uni", dial: "+44" },
    { code: "GD", name: "Grenade", dial: "+1" },
    { code: "GE", name: "Géorgie", dial: "+995" },
    { code: "GF", name: "Guyane française", dial: "+594" },
    { code: "GG", name: "Guernesey", dial: "+44" },
    { code: "GH", name: "Ghana", dial: "+233" },
    { code: "GI", name: "Gibraltar", dial: "+350" },
    { code: "GL", name: "Groenland", dial: "+299" },
    { code: "GM", name: "Gambie", dial: "+220" },
    { code: "GN", name: "Guinée", dial: "+224" },
    { code: "GP", name: "Guadeloupe", dial: "+590" },
    { code: "GQ", name: "Guinée équatoriale", dial: "+240" },
    { code: "GR", name: "Grèce", dial: "+30" },
    { code: "GT", name: "Guatemala", dial: "+502" },
    { code: "GU", name: "Guam", dial: "+1" },
    { code: "GW", name: "Guinée-Bissau", dial: "+245" },
    { code: "GY", name: "Guyana", dial: "+592" },
    { code: "HK", name: "Hong Kong", dial: "+852" },
    { code: "HN", name: "Honduras", dial: "+504" },
    { code: "HR", name: "Croatie", dial: "+385" },
    { code: "HT", name: "Haïti", dial: "+509" },
    { code: "HU", name: "Hongrie", dial: "+36" },
    { code: "ID", name: "Indonésie", dial: "+62" },
    { code: "IE", name: "Irlande", dial: "+353" },
    { code: "IL", name: "Israël", dial: "+972" },
    { code: "IM", name: "Île de Man", dial: "+44" },
    { code: "IN", name: "Inde", dial: "+91" },
    { code: "IO", name: "Territoire britannique de l'océan Indien", dial: "+246" },
    { code: "IQ", name: "Irak", dial: "+964" },
    { code: "IR", name: "Iran", dial: "+98" },
    { code: "IS", name: "Islande", dial: "+354" },
    { code: "IT", name: "Italie", dial: "+39" },
    { code: "JE", name: "Jersey", dial: "+44" },
    { code: "JM", name: "Jamaïque", dial: "+1" },
    { code: "JO", name: "Jordanie", dial: "+962" },
    { code: "JP", name: "Japon", dial: "+81" },
    { code: "KE", name: "Kenya", dial: "+254" },
    { code: "KG", name: "Kirghizistan", dial: "+996" },
    { code: "KH", name: "Cambodge", dial: "+855" },
    { code: "KI", name: "Kiribati", dial: "+686" },
    { code: "KM", name: "Comores", dial: "+269" },
    { code: "KN", name: "Saint-Kitts-et-Nevis", dial: "+1" },
    { code: "KP", name: "Corée du Nord", dial: "+850" },
    { code: "KR", name: "Corée du Sud", dial: "+82" },
    { code: "KW", name: "Koweït", dial: "+965" },
    { code: "KY", name: "Îles Caïmans", dial: "+1" },
    { code: "KZ", name: "Kazakhstan", dial: "+7" },
    { code: "LA", name: "Laos", dial: "+856" },
    { code: "LB", name: "Liban", dial: "+961" },
    { code: "LC", name: "Sainte-Lucie", dial: "+1" },
    { code: "LI", name: "Liechtenstein", dial: "+423" },
    { code: "LK", name: "Sri Lanka", dial: "+94" },
    { code: "LR", name: "Liberia", dial: "+231" },
    { code: "LS", name: "Lesotho", dial: "+266" },
    { code: "LT", name: "Lituanie", dial: "+370" },
    { code: "LU", name: "Luxembourg", dial: "+352" },
    { code: "LV", name: "Lettonie", dial: "+371" },
    { code: "LY", name: "Libye", dial: "+218" },
    { code: "MA", name: "Maroc", dial: "+212" },
    { code: "MC", name: "Monaco", dial: "+377" },
    { code: "MD", name: "Moldavie", dial: "+373" },
    { code: "ME", name: "Monténégro", dial: "+382" },
    { code: "MF", name: "Saint-Martin", dial: "+590" },
    { code: "MG", name: "Madagascar", dial: "+261" },
    { code: "MH", name: "Îles Marshall", dial: "+692" },
    { code: "MK", name: "Macédoine du Nord", dial: "+389" },
    { code: "ML", name: "Mali", dial: "+223" },
    { code: "MM", name: "Myanmar", dial: "+95" },
    { code: "MN", name: "Mongolie", dial: "+976" },
    { code: "MO", name: "Macao", dial: "+853" },
    { code: "MP", name: "Îles Mariannes", dial: "+1" },
    { code: "MQ", name: "Martinique", dial: "+596" },
    { code: "MR", name: "Mauritanie", dial: "+222" },
    { code: "MS", name: "Montserrat", dial: "+1" },
    { code: "MT", name: "Malte", dial: "+356" },
    { code: "MU", name: "Maurice", dial: "+230" },
    { code: "MV", name: "Maldives", dial: "+960" },
    { code: "MW", name: "Malawi", dial: "+265" },
    { code: "MX", name: "Mexique", dial: "+52" },
    { code: "MY", name: "Malaisie", dial: "+60" },
    { code: "MZ", name: "Mozambique", dial: "+258" },
    { code: "NA", name: "Namibie", dial: "+264" },
    { code: "NC", name: "Nouvelle-Calédonie", dial: "+687" },
    { code: "NE", name: "Niger", dial: "+227" },
    { code: "NF", name: "Île Norfolk", dial: "+672" },
    { code: "NG", name: "Nigeria", dial: "+234" },
    { code: "NI", name: "Nicaragua", dial: "+505" },
    { code: "NL", name: "Pays-Bas", dial: "+31" },
    { code: "NO", name: "Norvège", dial: "+47" },
    { code: "NP", name: "Népal", dial: "+977" },
    { code: "NR", name: "Nauru", dial: "+674" },
    { code: "NU", name: "Niue", dial: "+683" },
    { code: "NZ", name: "Nouvelle-Zélande", dial: "+64" },
    { code: "OM", name: "Oman", dial: "+968" },
    { code: "PA", name: "Panama", dial: "+507" },
    { code: "PE", name: "Pérou", dial: "+51" },
    { code: "PF", name: "Polynésie française", dial: "+689" },
    { code: "PG", name: "Papouasie-Nouvelle-Guinée", dial: "+675" },
    { code: "PH", name: "Philippines", dial: "+63" },
    { code: "PK", name: "Pakistan", dial: "+92" },
    { code: "PL", name: "Pologne", dial: "+48" },
    { code: "PM", name: "Saint-Pierre-et-Miquelon", dial: "+508" },
    { code: "PR", name: "Porto Rico", dial: "+1" },
    { code: "PS", name: "Palestine", dial: "+970" },
    { code: "PT", name: "Portugal", dial: "+351" },
    { code: "PW", name: "Palaos", dial: "+680" },
    { code: "PY", name: "Paraguay", dial: "+595" },
    { code: "QA", name: "Qatar", dial: "+974" },
    { code: "RE", name: "La Réunion", dial: "+262" },
    { code: "RO", name: "Roumanie", dial: "+40" },
    { code: "RS", name: "Serbie", dial: "+381" },
    { code: "RU", name: "Russie", dial: "+7" },
    { code: "RW", name: "Rwanda", dial: "+250" },
    { code: "SA", name: "Arabie Saoudite", dial: "+966" },
    { code: "SB", name: "Îles Salomon", dial: "+677" },
    { code: "SC", name: "Seychelles", dial: "+248" },
    { code: "SD", name: "Soudan", dial: "+249" },
    { code: "SE", name: "Suède", dial: "+46" },
    { code: "SG", name: "Singapour", dial: "+65" },
    { code: "SH", name: "Sainte-Hélène", dial: "+290" },
    { code: "SI", name: "Slovénie", dial: "+386" },
    { code: "SJ", name: "Svalbard et Jan Mayen", dial: "+47" },
    { code: "SK", name: "Slovaquie", dial: "+421" },
    { code: "SL", name: "Sierra Leone", dial: "+232" },
    { code: "SM", name: "Saint-Marin", dial: "+378" },
    { code: "SN", name: "Sénégal", dial: "+221" },
    { code: "SO", name: "Somalie", dial: "+252" },
    { code: "SR", name: "Suriname", dial: "+597" },
    { code: "SS", name: "Soudan du Sud", dial: "+211" },
    { code: "ST", name: "São Tomé-et-Príncipe", dial: "+239" },
    { code: "SV", name: "El Salvador", dial: "+503" },
    { code: "SX", name: "Saint-Martin (Pays-Bas)", dial: "+1" },
    { code: "SY", name: "Syrie", dial: "+963" },
    { code: "SZ", name: "Eswatini", dial: "+268" },
    { code: "TA", name: "Tristan da Cunha", dial: "+290" },
    { code: "TC", name: "Îles Turques-et-Caïques", dial: "+1" },
    { code: "TD", name: "Tchad", dial: "+235" },
    { code: "TG", name: "Togo", dial: "+228" },
    { code: "TH", name: "Thaïlande", dial: "+66" },
    { code: "TJ", name: "Tadjikistan", dial: "+992" },
    { code: "TK", name: "Tokelau", dial: "+690" },
    { code: "TL", name: "Timor oriental", dial: "+670" },
    { code: "TM", name: "Turkménistan", dial: "+993" },
    { code: "TN", name: "Tunisie", dial: "+216" },
    { code: "TO", name: "Tonga", dial: "+676" },
    { code: "TR", name: "Turquie", dial: "+90" },
    { code: "TT", name: "Trinité-et-Tobago", dial: "+1" },
    { code: "TV", name: "Tuvalu", dial: "+688" },
    { code: "TW", name: "Taïwan", dial: "+886" },
    { code: "TZ", name: "Tanzanie", dial: "+255" },
    { code: "UA", name: "Ukraine", dial: "+380" },
    { code: "UG", name: "Ouganda", dial: "+256" },
    { code: "US", name: "États-Unis", dial: "+1" },
    { code: "UY", name: "Uruguay", dial: "+598" },
    { code: "UZ", name: "Ouzbékistan", dial: "+998" },
    { code: "VA", name: "Vatican", dial: "+39" },
    { code: "VC", name: "Saint-Vincent-et-les-Grenadines", dial: "+1" },
    { code: "VE", name: "Venezuela", dial: "+58" },
    { code: "VG", name: "Îles Vierges britanniques", dial: "+1" },
    { code: "VI", name: "Îles Vierges américaines", dial: "+1" },
    { code: "VN", name: "Viêt Nam", dial: "+84" },
    { code: "VU", name: "Vanuatu", dial: "+678" },
    { code: "WF", name: "Wallis-et-Futuna", dial: "+681" },
    { code: "WS", name: "Samoa", dial: "+685" },
    { code: "XK", name: "Kosovo", dial: "+383" },
    { code: "YE", name: "Yémen", dial: "+967" },
    { code: "YT", name: "Mayotte", dial: "+262" },
    { code: "ZA", name: "Afrique du Sud", dial: "+27" },
    { code: "ZM", name: "Zambie", dial: "+260" },
    { code: "ZW", name: "Zimbabwe", dial: "+263" },
];

// Priority countries shown at top of picker (West/Central Africa focus)
export const PRIORITY_COUNTRY_CODES = [
    "SN", "CI", "BJ", "TG", "ML", "BF", "CM", "GN", "NE", "CD",
    "CG", "GA", "TD", "MG", "MR", "FR", "US", "GB", "CA",
];

export function getCountryByCode(code: string): Country | undefined {
    return COUNTRIES.find(c => c.code === code);
}

export function getCountryByName(name: string): Country | undefined {
    const lower = name.toLowerCase();
    return COUNTRIES.find(c => c.name.toLowerCase() === lower);
}
